// Saforia - Export Utilities
// Download data as JSON, CSV, or self-contained HTML report.

function downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

export function exportJSON(data, filename = 'saforia-export.json') {
    const json = JSON.stringify(data, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    downloadBlob(blob, filename);
}

export function exportCSV(rows, headers, filename = 'saforia-export.csv') {
    if (!rows || rows.length === 0) return;

    const keys = headers || Object.keys(rows[0]);
    const csvLines = [keys.join(',')];

    for (const row of rows) {
        const values = keys.map(k => {
            const val = row[k];
            if (val == null) return '';
            const str = String(val);
            // Escape quotes and wrap in quotes if contains comma, newline, or quote
            if (str.includes(',') || str.includes('\n') || str.includes('"')) {
                return '"' + str.replace(/"/g, '""') + '"';
            }
            return str;
        });
        csvLines.push(values.join(','));
    }

    const blob = new Blob([csvLines.join('\n')], { type: 'text/csv;charset=utf-8' });
    downloadBlob(blob, filename);
}

export function exportHTMLReport(htmlContent, filename = 'saforia-report.html') {
    const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Saforia - Safety Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; color: #1a1a2e; background: #fff; }
        h1 { font-size: 1.5rem; margin-bottom: 0.5rem; color: #1a56db; }
        h2 { font-size: 1.2rem; margin: 1.5rem 0 0.5rem; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.25rem; }
        h3 { font-size: 1rem; margin: 1rem 0 0.5rem; }
        table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }
        th, td { padding: 0.5rem; text-align: left; border: 1px solid #e5e7eb; }
        th { background: #f3f4f6; font-weight: 600; }
        .score { font-size: 2rem; font-weight: 700; }
        .safe { color: #059669; } .low { color: #0284c7; } .medium { color: #d97706; } .high { color: #dc2626; } .critical { color: #991b1b; }
        .badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; }
        .hash { font-family: monospace; font-size: 0.75rem; word-break: break-all; background: #f3f4f6; padding: 0.5rem; border-radius: 4px; }
        .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; font-size: 0.75rem; color: #6b7280; }
        @media print { body { padding: 1rem; } }
    </style>
</head>
<body>
${htmlContent}
<div class="footer">
    <p>Generated by Saforia - AI Safety Platform | Apache 2.0 License</p>
    <p>This report was generated locally. No data was transmitted to external servers.</p>
</div>
</body>
</html>`;
    const blob = new Blob([fullHTML], { type: 'text/html;charset=utf-8' });
    downloadBlob(blob, filename);
}
